name: Build and deploy on push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Build for production
        run: npm run build:prod
      - name: Deploy to firebase
        run: npm run deploy --token="$FIREBASE_TOKEN"
