name: Build and deploy on push

on:
  push:
    branches:
      - notifications

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # - name: Install dependencies
      #   run: npm install
      # - name: Build for production
      #   run: npm run build:prod
      # - name: Deploy to firebase
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      #   run: ./node_modules/.bin/firebase deploy --only hosting --token=${FIREBASE_TOKEN}
      - name: Install functions dependencies
        run: cd functions && npm install
      - name: Install firebase-tools
        run: npm i -g firebase-tools
      - name: Deploy functions to firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only functions --token=${FIREBASE_TOKEN}
